# Generated by Django 5.1.1 on 2024-09-20 14:20

import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('codigo', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='Código do Produto')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Produto')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade de Produto')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor do produto')),
                ('imagem', stdimage.models.StdImageField(force_min_size=False, upload_to='', variations={'thumb': (124, 124)}, verbose_name='Imagem do produto')),
            ],
        ),
    ]
